apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nodejs-hello
    name: nodejs-hello
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nodejs-hello
    name: nodejs-hello
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: nodejs-hello:latest
    postCommit: {}
    resources: {}
    source:
      contextDir: nodejs-helloworld
      git:
        ref: troubleshoot-s2i
        uri: http://github.com/rajkur12/DO180-apps
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: npm_config-registry
          value: http://nexus-common.apps.ocp-ap3.prod.nextcle.com/repository/npm-proxy
        from:
          kind: ImageStreamTag
          name: nodejs:8
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: hnVKTOg1TNo0lZ0PEzKm
      type: GitHub
    - generic:
        secret: RWxe5pcfiBpxzjBszFXA
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nodejs-hello
    name: nodejs-hello
  spec:
    replicas: 1
    selector:
      app: nodejs-hello
      deploymentconfig: nodejs-hello
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: nodejs-hello
          deploymentconfig: nodejs-hello
      spec:
        containers:
        - image: nodejs-hello:latest
          name: nodejs-hello
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - nodejs-hello
        from:
          kind: ImageStreamTag
          name: nodejs-hello:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nodejs-hello
    name: nodejs-hello
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: nodejs-hello
      deploymentconfig: nodejs-hello
  status:
    loadBalancer: {}
kind: List
metadata: {}
