apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: php-helloworld
    name: php-helloworld
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: php-helloworld
    name: php-helloworld
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: php-helloworld:latest
    postCommit: {}
    resources: {}
    source:
      contextDir: php-helloworld
      git:
        ref: s2i
        uri: https://github.com/rajkur12/DO180-apps
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: php:7.1
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: dMF14N1H7YCWwidV-Dhp
      type: GitHub
    - generic:
        secret: 6_zPNCC0Ke9H7Sq_u__y
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: php-helloworld
    name: php-helloworld
  spec:
    replicas: 2
    selector:
      app: php-helloworld
      deploymentconfig: php-helloworld
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: php-helloworld
          deploymentconfig: php-helloworld
      spec:
        containers:
        - image: php-helloworld:latest
          name: php-helloworld
          ports:
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - php-helloworld
        from:
          kind: ImageStreamTag
          name: php-helloworld:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: php-helloworld
    name: php-helloworld
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      app: php-helloworld
      deploymentconfig: php-helloworld
  status:
    loadBalancer: {}
kind: List
metadata: {}
